# Site settings
title: Listen to the voice in leaf
email: jingyania@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  聆听叶落的声音

baseurl: "http://jingyania.github.io"
github_username: jingyania
permalink: /:categories/:title.html

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
